version: "3.7"

services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - 5000:5432
    environment:
      - POSTGRES_DB=sport_booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - sportbook-net

  redis:
    container_name: redis
    image: 'redis:6.0-alpine'
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - sportbook-net

  sportbook-backend:
    container_name: sportbook-backend
    build:
      context: ../sportbook-backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 9000:9000
    environment:
      - NODE_ENV=development
      - PORT=9000
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=sport_booking
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    volumes:
      - ../sportbook-backend:/app
      - ../sportbook-backend/node_modules:/app/node_modules
    networks:
      - sportbook-net
    depends_on:
      - db
      - redis

  sportbook-worker:
    container_name: sportbook-worker
    build:
      context: ../sportbook-worker
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 9100:9100
    environment:
      - NODE_ENV=development
      - PORT=9100
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=sport_booking
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    volumes:
      - ../sportbook-worker:/app
      - ../sportbook-worker/node_modules:/app/node_modules
    networks:
      - sportbook-net
    depends_on:
      - db
      - redis

networks:
  sportbook-net:

volumes:
  db:
  redis:
